/*
Pulsar Admin REST API

This provides the REST API for admin operations

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CompletableFutureClusterData struct for CompletableFutureClusterData
type CompletableFutureClusterData struct {
	Done *bool `json:"done,omitempty"`
	CompletedExceptionally *bool `json:"completedExceptionally,omitempty"`
	NumberOfDependents *int32 `json:"numberOfDependents,omitempty"`
	Cancelled *bool `json:"cancelled,omitempty"`
}

// NewCompletableFutureClusterData instantiates a new CompletableFutureClusterData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompletableFutureClusterData() *CompletableFutureClusterData {
	this := CompletableFutureClusterData{}
	return &this
}

// NewCompletableFutureClusterDataWithDefaults instantiates a new CompletableFutureClusterData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompletableFutureClusterDataWithDefaults() *CompletableFutureClusterData {
	this := CompletableFutureClusterData{}
	return &this
}

// GetDone returns the Done field value if set, zero value otherwise.
func (o *CompletableFutureClusterData) GetDone() bool {
	if o == nil || o.Done == nil {
		var ret bool
		return ret
	}
	return *o.Done
}

// GetDoneOk returns a tuple with the Done field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompletableFutureClusterData) GetDoneOk() (*bool, bool) {
	if o == nil || o.Done == nil {
		return nil, false
	}
	return o.Done, true
}

// HasDone returns a boolean if a field has been set.
func (o *CompletableFutureClusterData) HasDone() bool {
	if o != nil && o.Done != nil {
		return true
	}

	return false
}

// SetDone gets a reference to the given bool and assigns it to the Done field.
func (o *CompletableFutureClusterData) SetDone(v bool) {
	o.Done = &v
}

// GetCompletedExceptionally returns the CompletedExceptionally field value if set, zero value otherwise.
func (o *CompletableFutureClusterData) GetCompletedExceptionally() bool {
	if o == nil || o.CompletedExceptionally == nil {
		var ret bool
		return ret
	}
	return *o.CompletedExceptionally
}

// GetCompletedExceptionallyOk returns a tuple with the CompletedExceptionally field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompletableFutureClusterData) GetCompletedExceptionallyOk() (*bool, bool) {
	if o == nil || o.CompletedExceptionally == nil {
		return nil, false
	}
	return o.CompletedExceptionally, true
}

// HasCompletedExceptionally returns a boolean if a field has been set.
func (o *CompletableFutureClusterData) HasCompletedExceptionally() bool {
	if o != nil && o.CompletedExceptionally != nil {
		return true
	}

	return false
}

// SetCompletedExceptionally gets a reference to the given bool and assigns it to the CompletedExceptionally field.
func (o *CompletableFutureClusterData) SetCompletedExceptionally(v bool) {
	o.CompletedExceptionally = &v
}

// GetNumberOfDependents returns the NumberOfDependents field value if set, zero value otherwise.
func (o *CompletableFutureClusterData) GetNumberOfDependents() int32 {
	if o == nil || o.NumberOfDependents == nil {
		var ret int32
		return ret
	}
	return *o.NumberOfDependents
}

// GetNumberOfDependentsOk returns a tuple with the NumberOfDependents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompletableFutureClusterData) GetNumberOfDependentsOk() (*int32, bool) {
	if o == nil || o.NumberOfDependents == nil {
		return nil, false
	}
	return o.NumberOfDependents, true
}

// HasNumberOfDependents returns a boolean if a field has been set.
func (o *CompletableFutureClusterData) HasNumberOfDependents() bool {
	if o != nil && o.NumberOfDependents != nil {
		return true
	}

	return false
}

// SetNumberOfDependents gets a reference to the given int32 and assigns it to the NumberOfDependents field.
func (o *CompletableFutureClusterData) SetNumberOfDependents(v int32) {
	o.NumberOfDependents = &v
}

// GetCancelled returns the Cancelled field value if set, zero value otherwise.
func (o *CompletableFutureClusterData) GetCancelled() bool {
	if o == nil || o.Cancelled == nil {
		var ret bool
		return ret
	}
	return *o.Cancelled
}

// GetCancelledOk returns a tuple with the Cancelled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompletableFutureClusterData) GetCancelledOk() (*bool, bool) {
	if o == nil || o.Cancelled == nil {
		return nil, false
	}
	return o.Cancelled, true
}

// HasCancelled returns a boolean if a field has been set.
func (o *CompletableFutureClusterData) HasCancelled() bool {
	if o != nil && o.Cancelled != nil {
		return true
	}

	return false
}

// SetCancelled gets a reference to the given bool and assigns it to the Cancelled field.
func (o *CompletableFutureClusterData) SetCancelled(v bool) {
	o.Cancelled = &v
}

func (o CompletableFutureClusterData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Done != nil {
		toSerialize["done"] = o.Done
	}
	if o.CompletedExceptionally != nil {
		toSerialize["completedExceptionally"] = o.CompletedExceptionally
	}
	if o.NumberOfDependents != nil {
		toSerialize["numberOfDependents"] = o.NumberOfDependents
	}
	if o.Cancelled != nil {
		toSerialize["cancelled"] = o.Cancelled
	}
	return json.Marshal(toSerialize)
}

type NullableCompletableFutureClusterData struct {
	value *CompletableFutureClusterData
	isSet bool
}

func (v NullableCompletableFutureClusterData) Get() *CompletableFutureClusterData {
	return v.value
}

func (v *NullableCompletableFutureClusterData) Set(val *CompletableFutureClusterData) {
	v.value = val
	v.isSet = true
}

func (v NullableCompletableFutureClusterData) IsSet() bool {
	return v.isSet
}

func (v *NullableCompletableFutureClusterData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompletableFutureClusterData(val *CompletableFutureClusterData) *NullableCompletableFutureClusterData {
	return &NullableCompletableFutureClusterData{value: val, isSet: true}
}

func (v NullableCompletableFutureClusterData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompletableFutureClusterData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


