/*
Pulsar Admin REST API

This provides the REST API for admin operations

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// DelayedDeliveryPolicies struct for DelayedDeliveryPolicies
type DelayedDeliveryPolicies struct {
	TickTime *int64 `json:"tickTime,omitempty"`
	Active *bool `json:"active,omitempty"`
}

// NewDelayedDeliveryPolicies instantiates a new DelayedDeliveryPolicies object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDelayedDeliveryPolicies() *DelayedDeliveryPolicies {
	this := DelayedDeliveryPolicies{}
	return &this
}

// NewDelayedDeliveryPoliciesWithDefaults instantiates a new DelayedDeliveryPolicies object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDelayedDeliveryPoliciesWithDefaults() *DelayedDeliveryPolicies {
	this := DelayedDeliveryPolicies{}
	return &this
}

// GetTickTime returns the TickTime field value if set, zero value otherwise.
func (o *DelayedDeliveryPolicies) GetTickTime() int64 {
	if o == nil || o.TickTime == nil {
		var ret int64
		return ret
	}
	return *o.TickTime
}

// GetTickTimeOk returns a tuple with the TickTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DelayedDeliveryPolicies) GetTickTimeOk() (*int64, bool) {
	if o == nil || o.TickTime == nil {
		return nil, false
	}
	return o.TickTime, true
}

// HasTickTime returns a boolean if a field has been set.
func (o *DelayedDeliveryPolicies) HasTickTime() bool {
	if o != nil && o.TickTime != nil {
		return true
	}

	return false
}

// SetTickTime gets a reference to the given int64 and assigns it to the TickTime field.
func (o *DelayedDeliveryPolicies) SetTickTime(v int64) {
	o.TickTime = &v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *DelayedDeliveryPolicies) GetActive() bool {
	if o == nil || o.Active == nil {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DelayedDeliveryPolicies) GetActiveOk() (*bool, bool) {
	if o == nil || o.Active == nil {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *DelayedDeliveryPolicies) HasActive() bool {
	if o != nil && o.Active != nil {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *DelayedDeliveryPolicies) SetActive(v bool) {
	o.Active = &v
}

func (o DelayedDeliveryPolicies) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.TickTime != nil {
		toSerialize["tickTime"] = o.TickTime
	}
	if o.Active != nil {
		toSerialize["active"] = o.Active
	}
	return json.Marshal(toSerialize)
}

type NullableDelayedDeliveryPolicies struct {
	value *DelayedDeliveryPolicies
	isSet bool
}

func (v NullableDelayedDeliveryPolicies) Get() *DelayedDeliveryPolicies {
	return v.value
}

func (v *NullableDelayedDeliveryPolicies) Set(val *DelayedDeliveryPolicies) {
	v.value = val
	v.isSet = true
}

func (v NullableDelayedDeliveryPolicies) IsSet() bool {
	return v.isSet
}

func (v *NullableDelayedDeliveryPolicies) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDelayedDeliveryPolicies(val *DelayedDeliveryPolicies) *NullableDelayedDeliveryPolicies {
	return &NullableDelayedDeliveryPolicies{value: val, isSet: true}
}

func (v NullableDelayedDeliveryPolicies) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDelayedDeliveryPolicies) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


