/*
Pulsar Admin REST API

This provides the REST API for admin operations

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// TopicStats struct for TopicStats
type TopicStats struct {
	AverageMsgSize *float64 `json:"averageMsgSize,omitempty"`
	BacklogSize *int64 `json:"backlogSize,omitempty"`
	BytesInCounter *int64 `json:"bytesInCounter,omitempty"`
	BytesOutCounter *int64 `json:"bytesOutCounter,omitempty"`
	DeduplicationStatus *string `json:"deduplicationStatus,omitempty"`
	MsgChunkPublished *bool `json:"msgChunkPublished,omitempty"`
	MsgInCounter *int64 `json:"msgInCounter,omitempty"`
	MsgOutCounter *int64 `json:"msgOutCounter,omitempty"`
	MsgRateIn *float64 `json:"msgRateIn,omitempty"`
	MsgRateOut *float64 `json:"msgRateOut,omitempty"`
	MsgThroughputIn *float64 `json:"msgThroughputIn,omitempty"`
	MsgThroughputOut *float64 `json:"msgThroughputOut,omitempty"`
	Publishers *[]PublisherStats `json:"publishers,omitempty"`
	Replication *map[string]ReplicatorStats `json:"replication,omitempty"`
	StorageSize *int64 `json:"storageSize,omitempty"`
	Subscriptions *map[string]SubscriptionStats `json:"subscriptions,omitempty"`
}

// NewTopicStats instantiates a new TopicStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTopicStats() *TopicStats {
	this := TopicStats{}
	return &this
}

// NewTopicStatsWithDefaults instantiates a new TopicStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTopicStatsWithDefaults() *TopicStats {
	this := TopicStats{}
	return &this
}

// GetAverageMsgSize returns the AverageMsgSize field value if set, zero value otherwise.
func (o *TopicStats) GetAverageMsgSize() float64 {
	if o == nil || o.AverageMsgSize == nil {
		var ret float64
		return ret
	}
	return *o.AverageMsgSize
}

// GetAverageMsgSizeOk returns a tuple with the AverageMsgSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopicStats) GetAverageMsgSizeOk() (*float64, bool) {
	if o == nil || o.AverageMsgSize == nil {
		return nil, false
	}
	return o.AverageMsgSize, true
}

// HasAverageMsgSize returns a boolean if a field has been set.
func (o *TopicStats) HasAverageMsgSize() bool {
	if o != nil && o.AverageMsgSize != nil {
		return true
	}

	return false
}

// SetAverageMsgSize gets a reference to the given float64 and assigns it to the AverageMsgSize field.
func (o *TopicStats) SetAverageMsgSize(v float64) {
	o.AverageMsgSize = &v
}

// GetBacklogSize returns the BacklogSize field value if set, zero value otherwise.
func (o *TopicStats) GetBacklogSize() int64 {
	if o == nil || o.BacklogSize == nil {
		var ret int64
		return ret
	}
	return *o.BacklogSize
}

// GetBacklogSizeOk returns a tuple with the BacklogSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopicStats) GetBacklogSizeOk() (*int64, bool) {
	if o == nil || o.BacklogSize == nil {
		return nil, false
	}
	return o.BacklogSize, true
}

// HasBacklogSize returns a boolean if a field has been set.
func (o *TopicStats) HasBacklogSize() bool {
	if o != nil && o.BacklogSize != nil {
		return true
	}

	return false
}

// SetBacklogSize gets a reference to the given int64 and assigns it to the BacklogSize field.
func (o *TopicStats) SetBacklogSize(v int64) {
	o.BacklogSize = &v
}

// GetBytesInCounter returns the BytesInCounter field value if set, zero value otherwise.
func (o *TopicStats) GetBytesInCounter() int64 {
	if o == nil || o.BytesInCounter == nil {
		var ret int64
		return ret
	}
	return *o.BytesInCounter
}

// GetBytesInCounterOk returns a tuple with the BytesInCounter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopicStats) GetBytesInCounterOk() (*int64, bool) {
	if o == nil || o.BytesInCounter == nil {
		return nil, false
	}
	return o.BytesInCounter, true
}

// HasBytesInCounter returns a boolean if a field has been set.
func (o *TopicStats) HasBytesInCounter() bool {
	if o != nil && o.BytesInCounter != nil {
		return true
	}

	return false
}

// SetBytesInCounter gets a reference to the given int64 and assigns it to the BytesInCounter field.
func (o *TopicStats) SetBytesInCounter(v int64) {
	o.BytesInCounter = &v
}

// GetBytesOutCounter returns the BytesOutCounter field value if set, zero value otherwise.
func (o *TopicStats) GetBytesOutCounter() int64 {
	if o == nil || o.BytesOutCounter == nil {
		var ret int64
		return ret
	}
	return *o.BytesOutCounter
}

// GetBytesOutCounterOk returns a tuple with the BytesOutCounter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopicStats) GetBytesOutCounterOk() (*int64, bool) {
	if o == nil || o.BytesOutCounter == nil {
		return nil, false
	}
	return o.BytesOutCounter, true
}

// HasBytesOutCounter returns a boolean if a field has been set.
func (o *TopicStats) HasBytesOutCounter() bool {
	if o != nil && o.BytesOutCounter != nil {
		return true
	}

	return false
}

// SetBytesOutCounter gets a reference to the given int64 and assigns it to the BytesOutCounter field.
func (o *TopicStats) SetBytesOutCounter(v int64) {
	o.BytesOutCounter = &v
}

// GetDeduplicationStatus returns the DeduplicationStatus field value if set, zero value otherwise.
func (o *TopicStats) GetDeduplicationStatus() string {
	if o == nil || o.DeduplicationStatus == nil {
		var ret string
		return ret
	}
	return *o.DeduplicationStatus
}

// GetDeduplicationStatusOk returns a tuple with the DeduplicationStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopicStats) GetDeduplicationStatusOk() (*string, bool) {
	if o == nil || o.DeduplicationStatus == nil {
		return nil, false
	}
	return o.DeduplicationStatus, true
}

// HasDeduplicationStatus returns a boolean if a field has been set.
func (o *TopicStats) HasDeduplicationStatus() bool {
	if o != nil && o.DeduplicationStatus != nil {
		return true
	}

	return false
}

// SetDeduplicationStatus gets a reference to the given string and assigns it to the DeduplicationStatus field.
func (o *TopicStats) SetDeduplicationStatus(v string) {
	o.DeduplicationStatus = &v
}

// GetMsgChunkPublished returns the MsgChunkPublished field value if set, zero value otherwise.
func (o *TopicStats) GetMsgChunkPublished() bool {
	if o == nil || o.MsgChunkPublished == nil {
		var ret bool
		return ret
	}
	return *o.MsgChunkPublished
}

// GetMsgChunkPublishedOk returns a tuple with the MsgChunkPublished field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopicStats) GetMsgChunkPublishedOk() (*bool, bool) {
	if o == nil || o.MsgChunkPublished == nil {
		return nil, false
	}
	return o.MsgChunkPublished, true
}

// HasMsgChunkPublished returns a boolean if a field has been set.
func (o *TopicStats) HasMsgChunkPublished() bool {
	if o != nil && o.MsgChunkPublished != nil {
		return true
	}

	return false
}

// SetMsgChunkPublished gets a reference to the given bool and assigns it to the MsgChunkPublished field.
func (o *TopicStats) SetMsgChunkPublished(v bool) {
	o.MsgChunkPublished = &v
}

// GetMsgInCounter returns the MsgInCounter field value if set, zero value otherwise.
func (o *TopicStats) GetMsgInCounter() int64 {
	if o == nil || o.MsgInCounter == nil {
		var ret int64
		return ret
	}
	return *o.MsgInCounter
}

// GetMsgInCounterOk returns a tuple with the MsgInCounter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopicStats) GetMsgInCounterOk() (*int64, bool) {
	if o == nil || o.MsgInCounter == nil {
		return nil, false
	}
	return o.MsgInCounter, true
}

// HasMsgInCounter returns a boolean if a field has been set.
func (o *TopicStats) HasMsgInCounter() bool {
	if o != nil && o.MsgInCounter != nil {
		return true
	}

	return false
}

// SetMsgInCounter gets a reference to the given int64 and assigns it to the MsgInCounter field.
func (o *TopicStats) SetMsgInCounter(v int64) {
	o.MsgInCounter = &v
}

// GetMsgOutCounter returns the MsgOutCounter field value if set, zero value otherwise.
func (o *TopicStats) GetMsgOutCounter() int64 {
	if o == nil || o.MsgOutCounter == nil {
		var ret int64
		return ret
	}
	return *o.MsgOutCounter
}

// GetMsgOutCounterOk returns a tuple with the MsgOutCounter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopicStats) GetMsgOutCounterOk() (*int64, bool) {
	if o == nil || o.MsgOutCounter == nil {
		return nil, false
	}
	return o.MsgOutCounter, true
}

// HasMsgOutCounter returns a boolean if a field has been set.
func (o *TopicStats) HasMsgOutCounter() bool {
	if o != nil && o.MsgOutCounter != nil {
		return true
	}

	return false
}

// SetMsgOutCounter gets a reference to the given int64 and assigns it to the MsgOutCounter field.
func (o *TopicStats) SetMsgOutCounter(v int64) {
	o.MsgOutCounter = &v
}

// GetMsgRateIn returns the MsgRateIn field value if set, zero value otherwise.
func (o *TopicStats) GetMsgRateIn() float64 {
	if o == nil || o.MsgRateIn == nil {
		var ret float64
		return ret
	}
	return *o.MsgRateIn
}

// GetMsgRateInOk returns a tuple with the MsgRateIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopicStats) GetMsgRateInOk() (*float64, bool) {
	if o == nil || o.MsgRateIn == nil {
		return nil, false
	}
	return o.MsgRateIn, true
}

// HasMsgRateIn returns a boolean if a field has been set.
func (o *TopicStats) HasMsgRateIn() bool {
	if o != nil && o.MsgRateIn != nil {
		return true
	}

	return false
}

// SetMsgRateIn gets a reference to the given float64 and assigns it to the MsgRateIn field.
func (o *TopicStats) SetMsgRateIn(v float64) {
	o.MsgRateIn = &v
}

// GetMsgRateOut returns the MsgRateOut field value if set, zero value otherwise.
func (o *TopicStats) GetMsgRateOut() float64 {
	if o == nil || o.MsgRateOut == nil {
		var ret float64
		return ret
	}
	return *o.MsgRateOut
}

// GetMsgRateOutOk returns a tuple with the MsgRateOut field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopicStats) GetMsgRateOutOk() (*float64, bool) {
	if o == nil || o.MsgRateOut == nil {
		return nil, false
	}
	return o.MsgRateOut, true
}

// HasMsgRateOut returns a boolean if a field has been set.
func (o *TopicStats) HasMsgRateOut() bool {
	if o != nil && o.MsgRateOut != nil {
		return true
	}

	return false
}

// SetMsgRateOut gets a reference to the given float64 and assigns it to the MsgRateOut field.
func (o *TopicStats) SetMsgRateOut(v float64) {
	o.MsgRateOut = &v
}

// GetMsgThroughputIn returns the MsgThroughputIn field value if set, zero value otherwise.
func (o *TopicStats) GetMsgThroughputIn() float64 {
	if o == nil || o.MsgThroughputIn == nil {
		var ret float64
		return ret
	}
	return *o.MsgThroughputIn
}

// GetMsgThroughputInOk returns a tuple with the MsgThroughputIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopicStats) GetMsgThroughputInOk() (*float64, bool) {
	if o == nil || o.MsgThroughputIn == nil {
		return nil, false
	}
	return o.MsgThroughputIn, true
}

// HasMsgThroughputIn returns a boolean if a field has been set.
func (o *TopicStats) HasMsgThroughputIn() bool {
	if o != nil && o.MsgThroughputIn != nil {
		return true
	}

	return false
}

// SetMsgThroughputIn gets a reference to the given float64 and assigns it to the MsgThroughputIn field.
func (o *TopicStats) SetMsgThroughputIn(v float64) {
	o.MsgThroughputIn = &v
}

// GetMsgThroughputOut returns the MsgThroughputOut field value if set, zero value otherwise.
func (o *TopicStats) GetMsgThroughputOut() float64 {
	if o == nil || o.MsgThroughputOut == nil {
		var ret float64
		return ret
	}
	return *o.MsgThroughputOut
}

// GetMsgThroughputOutOk returns a tuple with the MsgThroughputOut field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopicStats) GetMsgThroughputOutOk() (*float64, bool) {
	if o == nil || o.MsgThroughputOut == nil {
		return nil, false
	}
	return o.MsgThroughputOut, true
}

// HasMsgThroughputOut returns a boolean if a field has been set.
func (o *TopicStats) HasMsgThroughputOut() bool {
	if o != nil && o.MsgThroughputOut != nil {
		return true
	}

	return false
}

// SetMsgThroughputOut gets a reference to the given float64 and assigns it to the MsgThroughputOut field.
func (o *TopicStats) SetMsgThroughputOut(v float64) {
	o.MsgThroughputOut = &v
}

// GetPublishers returns the Publishers field value if set, zero value otherwise.
func (o *TopicStats) GetPublishers() []PublisherStats {
	if o == nil || o.Publishers == nil {
		var ret []PublisherStats
		return ret
	}
	return *o.Publishers
}

// GetPublishersOk returns a tuple with the Publishers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopicStats) GetPublishersOk() (*[]PublisherStats, bool) {
	if o == nil || o.Publishers == nil {
		return nil, false
	}
	return o.Publishers, true
}

// HasPublishers returns a boolean if a field has been set.
func (o *TopicStats) HasPublishers() bool {
	if o != nil && o.Publishers != nil {
		return true
	}

	return false
}

// SetPublishers gets a reference to the given []PublisherStats and assigns it to the Publishers field.
func (o *TopicStats) SetPublishers(v []PublisherStats) {
	o.Publishers = &v
}

// GetReplication returns the Replication field value if set, zero value otherwise.
func (o *TopicStats) GetReplication() map[string]ReplicatorStats {
	if o == nil || o.Replication == nil {
		var ret map[string]ReplicatorStats
		return ret
	}
	return *o.Replication
}

// GetReplicationOk returns a tuple with the Replication field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopicStats) GetReplicationOk() (*map[string]ReplicatorStats, bool) {
	if o == nil || o.Replication == nil {
		return nil, false
	}
	return o.Replication, true
}

// HasReplication returns a boolean if a field has been set.
func (o *TopicStats) HasReplication() bool {
	if o != nil && o.Replication != nil {
		return true
	}

	return false
}

// SetReplication gets a reference to the given map[string]ReplicatorStats and assigns it to the Replication field.
func (o *TopicStats) SetReplication(v map[string]ReplicatorStats) {
	o.Replication = &v
}

// GetStorageSize returns the StorageSize field value if set, zero value otherwise.
func (o *TopicStats) GetStorageSize() int64 {
	if o == nil || o.StorageSize == nil {
		var ret int64
		return ret
	}
	return *o.StorageSize
}

// GetStorageSizeOk returns a tuple with the StorageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopicStats) GetStorageSizeOk() (*int64, bool) {
	if o == nil || o.StorageSize == nil {
		return nil, false
	}
	return o.StorageSize, true
}

// HasStorageSize returns a boolean if a field has been set.
func (o *TopicStats) HasStorageSize() bool {
	if o != nil && o.StorageSize != nil {
		return true
	}

	return false
}

// SetStorageSize gets a reference to the given int64 and assigns it to the StorageSize field.
func (o *TopicStats) SetStorageSize(v int64) {
	o.StorageSize = &v
}

// GetSubscriptions returns the Subscriptions field value if set, zero value otherwise.
func (o *TopicStats) GetSubscriptions() map[string]SubscriptionStats {
	if o == nil || o.Subscriptions == nil {
		var ret map[string]SubscriptionStats
		return ret
	}
	return *o.Subscriptions
}

// GetSubscriptionsOk returns a tuple with the Subscriptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopicStats) GetSubscriptionsOk() (*map[string]SubscriptionStats, bool) {
	if o == nil || o.Subscriptions == nil {
		return nil, false
	}
	return o.Subscriptions, true
}

// HasSubscriptions returns a boolean if a field has been set.
func (o *TopicStats) HasSubscriptions() bool {
	if o != nil && o.Subscriptions != nil {
		return true
	}

	return false
}

// SetSubscriptions gets a reference to the given map[string]SubscriptionStats and assigns it to the Subscriptions field.
func (o *TopicStats) SetSubscriptions(v map[string]SubscriptionStats) {
	o.Subscriptions = &v
}

func (o TopicStats) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AverageMsgSize != nil {
		toSerialize["averageMsgSize"] = o.AverageMsgSize
	}
	if o.BacklogSize != nil {
		toSerialize["backlogSize"] = o.BacklogSize
	}
	if o.BytesInCounter != nil {
		toSerialize["bytesInCounter"] = o.BytesInCounter
	}
	if o.BytesOutCounter != nil {
		toSerialize["bytesOutCounter"] = o.BytesOutCounter
	}
	if o.DeduplicationStatus != nil {
		toSerialize["deduplicationStatus"] = o.DeduplicationStatus
	}
	if o.MsgChunkPublished != nil {
		toSerialize["msgChunkPublished"] = o.MsgChunkPublished
	}
	if o.MsgInCounter != nil {
		toSerialize["msgInCounter"] = o.MsgInCounter
	}
	if o.MsgOutCounter != nil {
		toSerialize["msgOutCounter"] = o.MsgOutCounter
	}
	if o.MsgRateIn != nil {
		toSerialize["msgRateIn"] = o.MsgRateIn
	}
	if o.MsgRateOut != nil {
		toSerialize["msgRateOut"] = o.MsgRateOut
	}
	if o.MsgThroughputIn != nil {
		toSerialize["msgThroughputIn"] = o.MsgThroughputIn
	}
	if o.MsgThroughputOut != nil {
		toSerialize["msgThroughputOut"] = o.MsgThroughputOut
	}
	if o.Publishers != nil {
		toSerialize["publishers"] = o.Publishers
	}
	if o.Replication != nil {
		toSerialize["replication"] = o.Replication
	}
	if o.StorageSize != nil {
		toSerialize["storageSize"] = o.StorageSize
	}
	if o.Subscriptions != nil {
		toSerialize["subscriptions"] = o.Subscriptions
	}
	return json.Marshal(toSerialize)
}

type NullableTopicStats struct {
	value *TopicStats
	isSet bool
}

func (v NullableTopicStats) Get() *TopicStats {
	return v.value
}

func (v *NullableTopicStats) Set(val *TopicStats) {
	v.value = val
	v.isSet = true
}

func (v NullableTopicStats) IsSet() bool {
	return v.isSet
}

func (v *NullableTopicStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTopicStats(val *TopicStats) *NullableTopicStats {
	return &NullableTopicStats{value: val, isSet: true}
}

func (v NullableTopicStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTopicStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


