/*
Pulsar Admin REST API

This provides the REST API for admin operations

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ClusterData The configuration data for a cluster
type ClusterData struct {
	// The broker service url (for produce and consume operations)
	BrokerServiceUrl *string `json:"brokerServiceUrl,omitempty"`
	// The secured broker service url (for produce and consume operations)
	BrokerServiceUrlTls *string `json:"brokerServiceUrlTls,omitempty"`
	// A set of peer cluster names
	PeerClusterNames *[]string `json:"peerClusterNames,omitempty"`
	// protocol to decide type of proxy routing eg: SNI-routing
	ProxyProtocol *string `json:"proxyProtocol,omitempty"`
	// Proxy-service url when client would like to connect to broker via proxy.
	ProxyServiceUrl *string `json:"proxyServiceUrl,omitempty"`
	// The HTTP rest service URL (for admin operations)
	ServiceUrl *string `json:"serviceUrl,omitempty"`
	// The HTTPS rest service URL (for admin operations)
	ServiceUrlTls *string `json:"serviceUrlTls,omitempty"`
}

// NewClusterData instantiates a new ClusterData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterData() *ClusterData {
	this := ClusterData{}
	return &this
}

// NewClusterDataWithDefaults instantiates a new ClusterData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterDataWithDefaults() *ClusterData {
	this := ClusterData{}
	return &this
}

// GetBrokerServiceUrl returns the BrokerServiceUrl field value if set, zero value otherwise.
func (o *ClusterData) GetBrokerServiceUrl() string {
	if o == nil || o.BrokerServiceUrl == nil {
		var ret string
		return ret
	}
	return *o.BrokerServiceUrl
}

// GetBrokerServiceUrlOk returns a tuple with the BrokerServiceUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterData) GetBrokerServiceUrlOk() (*string, bool) {
	if o == nil || o.BrokerServiceUrl == nil {
		return nil, false
	}
	return o.BrokerServiceUrl, true
}

// HasBrokerServiceUrl returns a boolean if a field has been set.
func (o *ClusterData) HasBrokerServiceUrl() bool {
	if o != nil && o.BrokerServiceUrl != nil {
		return true
	}

	return false
}

// SetBrokerServiceUrl gets a reference to the given string and assigns it to the BrokerServiceUrl field.
func (o *ClusterData) SetBrokerServiceUrl(v string) {
	o.BrokerServiceUrl = &v
}

// GetBrokerServiceUrlTls returns the BrokerServiceUrlTls field value if set, zero value otherwise.
func (o *ClusterData) GetBrokerServiceUrlTls() string {
	if o == nil || o.BrokerServiceUrlTls == nil {
		var ret string
		return ret
	}
	return *o.BrokerServiceUrlTls
}

// GetBrokerServiceUrlTlsOk returns a tuple with the BrokerServiceUrlTls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterData) GetBrokerServiceUrlTlsOk() (*string, bool) {
	if o == nil || o.BrokerServiceUrlTls == nil {
		return nil, false
	}
	return o.BrokerServiceUrlTls, true
}

// HasBrokerServiceUrlTls returns a boolean if a field has been set.
func (o *ClusterData) HasBrokerServiceUrlTls() bool {
	if o != nil && o.BrokerServiceUrlTls != nil {
		return true
	}

	return false
}

// SetBrokerServiceUrlTls gets a reference to the given string and assigns it to the BrokerServiceUrlTls field.
func (o *ClusterData) SetBrokerServiceUrlTls(v string) {
	o.BrokerServiceUrlTls = &v
}

// GetPeerClusterNames returns the PeerClusterNames field value if set, zero value otherwise.
func (o *ClusterData) GetPeerClusterNames() []string {
	if o == nil || o.PeerClusterNames == nil {
		var ret []string
		return ret
	}
	return *o.PeerClusterNames
}

// GetPeerClusterNamesOk returns a tuple with the PeerClusterNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterData) GetPeerClusterNamesOk() (*[]string, bool) {
	if o == nil || o.PeerClusterNames == nil {
		return nil, false
	}
	return o.PeerClusterNames, true
}

// HasPeerClusterNames returns a boolean if a field has been set.
func (o *ClusterData) HasPeerClusterNames() bool {
	if o != nil && o.PeerClusterNames != nil {
		return true
	}

	return false
}

// SetPeerClusterNames gets a reference to the given []string and assigns it to the PeerClusterNames field.
func (o *ClusterData) SetPeerClusterNames(v []string) {
	o.PeerClusterNames = &v
}

// GetProxyProtocol returns the ProxyProtocol field value if set, zero value otherwise.
func (o *ClusterData) GetProxyProtocol() string {
	if o == nil || o.ProxyProtocol == nil {
		var ret string
		return ret
	}
	return *o.ProxyProtocol
}

// GetProxyProtocolOk returns a tuple with the ProxyProtocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterData) GetProxyProtocolOk() (*string, bool) {
	if o == nil || o.ProxyProtocol == nil {
		return nil, false
	}
	return o.ProxyProtocol, true
}

// HasProxyProtocol returns a boolean if a field has been set.
func (o *ClusterData) HasProxyProtocol() bool {
	if o != nil && o.ProxyProtocol != nil {
		return true
	}

	return false
}

// SetProxyProtocol gets a reference to the given string and assigns it to the ProxyProtocol field.
func (o *ClusterData) SetProxyProtocol(v string) {
	o.ProxyProtocol = &v
}

// GetProxyServiceUrl returns the ProxyServiceUrl field value if set, zero value otherwise.
func (o *ClusterData) GetProxyServiceUrl() string {
	if o == nil || o.ProxyServiceUrl == nil {
		var ret string
		return ret
	}
	return *o.ProxyServiceUrl
}

// GetProxyServiceUrlOk returns a tuple with the ProxyServiceUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterData) GetProxyServiceUrlOk() (*string, bool) {
	if o == nil || o.ProxyServiceUrl == nil {
		return nil, false
	}
	return o.ProxyServiceUrl, true
}

// HasProxyServiceUrl returns a boolean if a field has been set.
func (o *ClusterData) HasProxyServiceUrl() bool {
	if o != nil && o.ProxyServiceUrl != nil {
		return true
	}

	return false
}

// SetProxyServiceUrl gets a reference to the given string and assigns it to the ProxyServiceUrl field.
func (o *ClusterData) SetProxyServiceUrl(v string) {
	o.ProxyServiceUrl = &v
}

// GetServiceUrl returns the ServiceUrl field value if set, zero value otherwise.
func (o *ClusterData) GetServiceUrl() string {
	if o == nil || o.ServiceUrl == nil {
		var ret string
		return ret
	}
	return *o.ServiceUrl
}

// GetServiceUrlOk returns a tuple with the ServiceUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterData) GetServiceUrlOk() (*string, bool) {
	if o == nil || o.ServiceUrl == nil {
		return nil, false
	}
	return o.ServiceUrl, true
}

// HasServiceUrl returns a boolean if a field has been set.
func (o *ClusterData) HasServiceUrl() bool {
	if o != nil && o.ServiceUrl != nil {
		return true
	}

	return false
}

// SetServiceUrl gets a reference to the given string and assigns it to the ServiceUrl field.
func (o *ClusterData) SetServiceUrl(v string) {
	o.ServiceUrl = &v
}

// GetServiceUrlTls returns the ServiceUrlTls field value if set, zero value otherwise.
func (o *ClusterData) GetServiceUrlTls() string {
	if o == nil || o.ServiceUrlTls == nil {
		var ret string
		return ret
	}
	return *o.ServiceUrlTls
}

// GetServiceUrlTlsOk returns a tuple with the ServiceUrlTls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterData) GetServiceUrlTlsOk() (*string, bool) {
	if o == nil || o.ServiceUrlTls == nil {
		return nil, false
	}
	return o.ServiceUrlTls, true
}

// HasServiceUrlTls returns a boolean if a field has been set.
func (o *ClusterData) HasServiceUrlTls() bool {
	if o != nil && o.ServiceUrlTls != nil {
		return true
	}

	return false
}

// SetServiceUrlTls gets a reference to the given string and assigns it to the ServiceUrlTls field.
func (o *ClusterData) SetServiceUrlTls(v string) {
	o.ServiceUrlTls = &v
}

func (o ClusterData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.BrokerServiceUrl != nil {
		toSerialize["brokerServiceUrl"] = o.BrokerServiceUrl
	}
	if o.BrokerServiceUrlTls != nil {
		toSerialize["brokerServiceUrlTls"] = o.BrokerServiceUrlTls
	}
	if o.PeerClusterNames != nil {
		toSerialize["peerClusterNames"] = o.PeerClusterNames
	}
	if o.ProxyProtocol != nil {
		toSerialize["proxyProtocol"] = o.ProxyProtocol
	}
	if o.ProxyServiceUrl != nil {
		toSerialize["proxyServiceUrl"] = o.ProxyServiceUrl
	}
	if o.ServiceUrl != nil {
		toSerialize["serviceUrl"] = o.ServiceUrl
	}
	if o.ServiceUrlTls != nil {
		toSerialize["serviceUrlTls"] = o.ServiceUrlTls
	}
	return json.Marshal(toSerialize)
}

type NullableClusterData struct {
	value *ClusterData
	isSet bool
}

func (v NullableClusterData) Get() *ClusterData {
	return v.value
}

func (v *NullableClusterData) Set(val *ClusterData) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterData) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterData(val *ClusterData) *NullableClusterData {
	return &NullableClusterData{value: val, isSet: true}
}

func (v NullableClusterData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


